apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: governance-webhook
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: governance-webhook
  endpoints:
    - port: https
      path: /metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      interval: 15s
