apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: governance-webhook
webhooks:
  - name: governance-webhook.default.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kyverno
            - kube-system
            - cert-manager
            - monitoring
            - kubevirt
            - kubecost
    clientConfig:
      service:
        name: governance-webhook
        namespace: default
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZqakNDQTNhZ0F3SUJBZ0lVRXN0QUEvK2MyRjd5UGhVT2hnWW1LTEY0c1Y4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tURW5NQ1VHQTFVRUF3d2VaMjkyWlhKdVlXNWpaUzEzWldKb2IyOXJMbVJsWm1GMWJIUXVjM1pqTUI0WApEVEkyTURZeE9ERXdOVGMwTUZvWERUSTNNRFl4T0RFd05UYzBNRm93S1RFbk1DVUdBMVVFQXd3ZVoyOTJaWEp1CllXNWpaUzEzWldKb2IyOXJMbVJsWm1GMWJIUXVjM1pqTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEEKTUlJQ0NnS0NBZ0VBMm1CWlFqaU1qY0hhUGJVUVRCcE51YzdzYTNIOTQzN0t0ZVB6cStKWDg4Z1hrQlVMY1NKaAppeWx0VDlVcDNrMWhsT0ZWMDlNQzlDMjJzNjNUV2NtUUZqZEZBajhXS3JQQnZ2NlV2Qk9HQ2ViVEJhV2xrTTlCCnlxS0pkeW9rYlBPeGVPc1lUNFRFRWlvMk9vazAzRWtoMEhDVGN0SWw2UUJlaVN6M2QzUkVWWGZDdUNESmZ3anMKK01nczE4dmtTZGRsSGFBTDRQbUU5cWJFSXdHT3Z4b2VieTluTkpuUi9JeXdBRXhpakV4WHJuSmJmTFpWZFNpUQpwWGJJeVMxbWhGL1NPb2ZVdlM4OHdTRm9UMHR2SUFoTHdiVEkrZjF2cGRhcFVKd3dXTnhFVjF6SUpKdkd0L0hVClZqb2ozdHdOMERTdmN4K0RVcWdmcktNeUNldllGSURBOWtidWMvZjZoRkdZVThZc2d0eDdCYW9WWU41VVIwaXIKNlFTTm5EWE91aUlMUHpzWStFYnM1dng4ZTVwWk5oZWJWeEFsVG5Dbmc2M3haaWh2MzB3SnYrRTFDVzAzQ2ZIcAo0c253L2VNN0phNHR3dmh5alNaK2labHpTSUxoeGppYXBsbzRKb2piSU1VaXhndHFBdC9PNTd1ejNPNlVDa1RsCkprZmI0cUYxUGNhNG55TXFla0NLNGxmblhOck11by93dzNJT3VnTGNkUWdCWFYxc1hwODg0MVd2Y1hlYzJ3U1oKbWVnakNkVXBxMjZ0U1VjWnYvQVRWL3g3THZ1TVNoSnZDbDkwNlcrNlJNa0w1YUJDUVlKZnkzUDMxQ2hMWCtBMQpacDg1QXVxRlhxTC92a3dyU2ZaOEFtTUI1MnBzWUNtR1FnQ1dnR2tmU3p0WEk1UEhhTHRBc0kwQ0F3RUFBYU9CCnJUQ0JxakFkQmdOVkhRNEVGZ1FVcmxJcmtSWXV4QnEvdjFsdk5zRmNPbXhRclBRd0h3WURWUjBqQkJnd0ZvQVUKcmxJcmtSWXV4QnEvdjFsdk5zRmNPbXhRclBRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pCWEJnTlZIUkVFVURCTwpnaDVuYjNabGNtNWhibU5sTFhkbFltaHZiMnN1WkdWbVlYVnNkQzV6ZG1PQ0xHZHZkbVZ5Ym1GdVkyVXRkMlZpCmFHOXZheTVrWldaaGRXeDBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUMKQVFBM2tpTHR2ZnowMlZNbjZ3aFQwSHdoYTRrdDE2My9FMGxVWkkyZ0h3d3RJbC85RGNveWlYbmplaXp0SFRTRgphNEZPK2NOYXNvY3hpd1RUVHp5alE5dnZXbFQvbWNKR0k4OUI5TXNnQUR5ZkVoaXQwaVczQ245V2trOU5pbVJ3Cm05empkSzJlZEZyWHRyeW1tQ3RJSjRuMTRWUHpONjh2LzNheVJPREp3MTF2bGJUemg0ZWNsQlBkaDUxZGdKRU0KWkd0cytYVC9JbUM1Z002QUpJUVFVTGwxQWJXaXBKa2JDeEY4UVpldlB2K2gzSWJqSksyZ0MrbXMrSzBtV1pOUwpJOFlURHVFdUM0SVNlbUI1RnpyNnFyT1REZXB5OTQ1UVhnMnRqc3hTTGZBbC9sbVRqSDUySHB5SElEdk84dXN6CnZna3kvN3NBbzVpM0J6blpJbzBFaHVEVXp0U2c3bWw5SEZqVCtIR2dDTEk1dmJRN24yeUpvZFZMOE8xZ3RNb3IKZm9lZy9DNXE1K3ZFdTN5MFl3QzlxT3FiSWlRY0NEd0dKUjRLaTF3eGtCWFRyQ2FPTzFZc01yeXNxdUZVV1poLwptL0Fva3Rmb21pT2ZVTVdLb1RvMDRtOFZxODAvbk5aUmJXUXYveGhZbHhVbHJ6c2IzZGVpQUZuSmxsTzBrYlhyCmtPMmM3SXhJTGVYNFIrdFlEaDNsM3pGalZGek1MWU9jQ1Q4MzNNZWhvb2ErNFVkdkhxbW9GSzljZkV5TCswOWsKYXVVd21DVzRGTlN5Qk1UbDN6NU5oNVo2MEtWMGVnUTRISTZ5ejhxVWFVQmtHUnNVcjc1SUNkU1BJcUcvT0NoRQpRK1VtMGJPQ3FNdmRxNk5ReEVrV2REQXhUOE05aGpLd0FDaWt6TXM2dG50SnNRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
